### ISSUE TITLE
Example for ios project?

### ISSUE THREAD

**Issue by dinisnunes1** [asadmansr/Firebase-Test-Lab-Action#3]
It's working very well for android. Would it work too for ios projects? 

The firebase command is not that different:
`gcloud firebase test ios run --test PATH/TO/MyTests.zip \ --device model=iphonexr,version=13.2,locale=en_US,orientation=portrait --xcode-version=12.1`

Would this work with the current action, something like?

**tests.yml**
```
ios-iphonexr:
  type: instrumentation
  app: ''
  test: iosOutputZip.zip
  device:
    - model: iphonexr
      version: 13.2
      locale: 'en_US'
      orientation: portrait```

**Comment by adefemi171** [comment]
Hello @dinisnunes1 and @asadmansr  was wondering if you can share your workflow with me because I have this

```
name: Android CI

on:
  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run the Firebase Test Lab Action
      - name: Run tests on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: 'tests.yml:android-pixel-4'
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
```

And I keep having a failed job with the error `parse error: Invalid literal at line 2, column 0` was wondering what am doing wrong and also my tests.yml:android-pixel-4 is 

```
android-pixel-4:
  type: instrumentation
  app: app-debug.apk
  test: app-debug-androidTest.apk
  device:
    - model: flame
      version: 29
      locale: 'en'
      orientation: portrait
```
