### ISSUE TITLE
Set option for Enable Orchestrator

### ISSUE THREAD

**Issue by UtsavG93** [asadmansr/Firebase-Test-Lab-Action#4]
i want to run my Espresso Test with Orchestrator Enable, google have given below argument to set, so how to set the option? 
--use-orchestrator

**Comment by ckurtm** [comment]
you can already do this from the device spec file e.g.

```
virtual:
  type: instrumentation
  app: app/build/outputs/apk/dev/debug/app-dev-debug.apk
  test: app/build/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk
  use-orchestrator: true
  num-flaky-test-attempts: 1
  device:
    - { model: Pixel2, version: 30, locale: en } # Google Pixel 2
    - { model: Pixel2, version: 28, locale: en } # Google Pixel 2
```
